threads: 8
threads_eggnog: 8
mem:
  default: 250
  low: 20
  eggnog: 250

runtime:
  long: 24
  default: 10
  eggnog: 12
  short: 3

tmpdir: /tmp
clustermethod: linclust       # [cd-hit-est or mmseqs or linclust] see mmseqs for more detail
minid: 0.95                   # min id for gene clustering for the main gene catalog used for annotation
coverage: 0.8
extra: "--kmer-per-seq 80 --cov-mode 1"
SubsetSize: 500000

subclusterids:
  - 90
  - 50

compare_catalogs:
  gc90: "genecatalog/subcluster/gc90.fasta"
#  gc50: "genecatalog/subcluster/gc50.fasta"

query: "gc90"

compare_id: 0.9
