threads: 8
mem:
  default: 250
  low: 20
  eggnog: 250

runtime:
  long: 24
  default: 10
  eggnog: 12

tmpdir: /tmp
clustermethod: linclust       # [cd-hit-est or mmseqs or linclust] see mmseqs for more detail
minid: 0.95                   # min id for gene clustering for the main gene catalog used for annotation
coverage: 0.8
extra: "--kmer-per-seq 80 --cov-mode 1"
SubsetSize: 500000

subclusterids:
  - 90
  - 50
