threads: 8
mem: 90

tmpdir: /temp
clustermethod: linclust       # [cd-hit-est or mmseqs or linclust] see mmseqs for more details
minlength: 30
minid: 0.95                   # min id for gene clustering for the main gene catalog used for annotation
coverage: 0.9
extra: ""
SubsetSize: 500000
